name: API Runner CI/CD

on:
  push:
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: [self-hosted, api]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run API Deployment Script
      run: python ./api/repos.py
