name: Build and Deploy Runner Matrix

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner: [api, frontend, backend]
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker Image for ${{ matrix.runner }} Runner
        run: docker build -f runner/Dockerfile.runner -t my-${{ matrix.runner }}-runner .

      - name: Run Docker Container for ${{ matrix.runner }} Runner
        run: |
          docker run -d --name my-${{ matrix.runner }}-runner-container \
          -e REGISTRATION_TOKEN=${{ secrets.REGISTRATION_TOKEN }} \
          my-${{ matrix.runner }}-runner
