name: Build Frontend Container

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/build_frontend_container.yaml'

jobs:
  build-and-push:
    runs-on: [self-hosted, frontend]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: cdaprod/cda-frontend-runner:${{ github.sha }}
